# Generated by Django 5.1.7 on 2025-03-16 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menu_id'),
        ('orders', '0003_orders_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsmenuthrough',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='itemsmenuthrough',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
    ]
