# Generated by Django 5.1.7 on 2025-03-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_itemsmenuthrough_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Готов', 'Готов'), ('Оплачено', 'Оплачено')], default='В ожидании', max_length=20),
        ),
    ]
